//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookValue
    {
        public int Id { get; set; }
        public int BooksId { get; set; }
        public int ValueId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ValueAtt ValueAtt { get; set; }
    }
}
