//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueAtt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValueAtt()
        {
            this.BookValues = new HashSet<BookValue>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Cheked { get; set; }
        public string ValueText { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> ValueInt { get; set; }
        public Nullable<int> AttributesId { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookValue> BookValues { get; set; }
    }
}
